<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="LiveCharts.Wpf" Version="0.9.5" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.28" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ChuHo.cs\Domain.cs.csproj" />
	</ItemGroup>
</Project>