<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Server-7ad0e5f9-6f36-4c1d-9760-9e49a86d53be</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.16" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="MQTTnet" Version="5.0.0.1405" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ChuHo.cs\Domain.cs.csproj" />
    <ProjectReference Include="..\Data\Data.csproj" />
  </ItemGroup>
</Project>
